run:
  timeout: 5m

linters:
  enable:
    - gosec

linters-settings:
  gosec:
    excludes:
      - G204  # Subprocess launched with variable — CLI tool executes user-specified commands by design
      - G301  # Directory permissions — CLI tool creates project directories with standard 0755
      - G302  # OpenFile permissions — CLI tool writes config/log files with standard 0644
      - G304  # File inclusion via variable — CLI tool reads user-specified file paths by design
      - G306  # WriteFile permissions — CLI tool writes .env/config files with standard 0644
