# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for envref
# Docs: https://goreleaser.com

version: 2

project_name: envref

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: envref
    main: ./cmd/envref
    binary: envref
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/xcke/envref/internal/cmd.version={{.Version}}'

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^chore:"
      - "^test:"

brews:
  - repository:
      owner: xcke
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/xcke/envref"
    description: "CLI tool for separating config from secrets in .env files"
    license: "MIT"
    install: |
      bin.install "envref"
    test: |
      assert_match "envref", shell_output("#{bin}/envref --help")
    dependencies:
      - name: go
        type: build

aurs:
  - name: envref-bin
    homepage: "https://github.com/xcke/envref"
    description: "CLI tool for separating config from secrets in .env files"
    license: "MIT"
    maintainers:
      - "xcke <xcke@users.noreply.github.com>"
    contributors:
      - "xcke <xcke@users.noreply.github.com>"
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/envref-bin.git"
    provides:
      - envref
    conflicts:
      - envref
    depends:
      - glibc
    package: |-
      install -Dm755 "./envref" "${pkgdir}/usr/bin/envref"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/envref/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/envref/README.md"

release:
  github:
    owner: xcke
    name: envref
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
