# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for envref
# Docs: https://goreleaser.com

version: 2

project_name: envref

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: envref
    main: ./cmd/envref
    binary: envref
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/xcke/envref/internal/cmd.version={{.Version}}'

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^chore:"
      - "^test:"

release:
  github:
    owner: xcke
    name: envref
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
